use winapi::shared::ntdef::{HANDLE, NTSTATUS, OBJECT_ATTRIBUTES, POBJECT_ATTRIBUTES, PLARGE_INTEGER, PVOID, SIZE_T};
use winapi::um::winnt::{ACCESS_MASK, SECTION_MAP_READ, SECTION_MAP_EXECUTE};

fn main() {}
