@echo off
:: scripts/quickstart.bat — One command to go from git clone to running system.
::
:: What it does:
::   1. Checks for Rust toolchain
::   2. Builds orchestra-builder (release)
::   3. Generates a default outbound profile with random credentials
::   4. Generates a self-signed TLS certificate
::   5. Builds the agent payload (outbound-c mode)
::   6. Generates orchestra-server.toml with matching credentials
::   7. Builds the Orchestra Control Center
::   8. Prints dashboard URL, bearer token, and agent deployment command
::
:: Environment variables:
::   ORCHESTRA_PROFILE    — profile name (default: "default")
::   ORCHESTRA_HTTP_PORT  — dashboard HTTPS port (default: 8443)
::   ORCHESTRA_AGENT_PORT — agent listener port (default: 8444)
::   ORCHESTRA_SKIP_SERVER — set to "1" to skip starting the server
::
:: This script is intended for use on systems you own or manage.

setlocal enabledelayedexpansion

set "ROOT=%~dp0.."
pushd "%ROOT%" || goto :err
set "ROOT=%CD%"

set "PROFILE_NAME=%ORCHESTRA_PROFILE%"
if "%PROFILE_NAME%"=="" set "PROFILE_NAME=default"
set "HTTP_PORT=%ORCHESTRA_HTTP_PORT%"
if "%HTTP_PORT%"=="" set "HTTP_PORT=8443"
set "AGENT_PORT=%ORCHESTRA_AGENT_PORT%"
if "%AGENT_PORT%"=="" set "AGENT_PORT=8444"
set "SKIP_SERVER=%ORCHESTRA_SKIP_SERVER%"
if "%SKIP_SERVER%"=="" set "SKIP_SERVER=0"

set "PROFILE_PATH=profiles\%PROFILE_NAME%.toml"
set "SERVER_CFG=orchestra-server.toml"

echo.
echo   [quickstart] Orchestra Quickstart (Windows)
echo.

:: ── 1. Rust toolchain ───────────────────────────────────────────────────

where cargo >nul 2>&1
if %errorlevel% neq 0 (
    echo   [quickstart] ERROR: Rust toolchain ^(cargo^) not found on PATH.
    echo   [quickstart] Install Rust from https://rustup.rs and re-run.
    goto :err
)

for /f "tokens=*" %%v in ('cargo --version') do echo   [quickstart] %%v

:: ── 2. Builder ─────────────────────────────────────────────────────────

set "BUILDER_BIN=%ROOT%\target\release\orchestra-builder.exe"
if not exist "%BUILDER_BIN%" (
    echo   [quickstart] Building orchestra-builder ^(release^)...
    cargo build --release -p builder
    if %errorlevel% neq 0 goto :err
)

:: ── 3. Platform detection ──────────────────────────────────────────────

set "OS=windows"
set "ARCH=x86_64"
if "%PROCESSOR_ARCHITECTURE%"=="ARM64" set "ARCH=aarch64"

:: Detect LAN IP (best effort)
set "DETECTED_IP=127.0.0.1"
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /c:"IPv4" 2^>nul') do (
    for /f "tokens=1" %%b in ("%%a") do set "DETECTED_IP=%%b"
)

:: ── 4. Credentials ─────────────────────────────────────────────────────

if not exist "profiles" mkdir profiles
if not exist "dist"    mkdir dist
if not exist "secrets" mkdir secrets

:: Generate random bytes via PowerShell
powershell -Command "[Convert]::ToBase64String([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(32))" > "%TEMP%\orch_key.tmp"
set /p AES_KEY=<"%TEMP%\orch_key.tmp"
del "%TEMP%\orch_key.tmp"

powershell -Command "[Convert]::ToBase64String([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(32))" > "%TEMP%\orch_secret.tmp"
set /p AGENT_SECRET=<"%TEMP%\orch_secret.tmp"
del "%TEMP%\orch_secret.tmp"

powershell -Command "$b=[Convert]::ToBase64String([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(24)); $b.Replace('+','-').Replace('/','_').TrimEnd('=')" > "%TEMP%\orch_token.tmp"
set /p ADMIN_TOKEN=<"%TEMP%\orch_token.tmp"
del "%TEMP%\orch_token.tmp"

:: ── 5. TLS certificate ────────────────────────────────────────────────

set "CERT=secrets\server.crt"
set "KEY=secrets\server.key"

if not exist "%CERT%" (
    if not exist "%KEY%" (
        echo   [quickstart] Generating self-signed TLS cert...
        openssl req -x509 -nodes -newkey ec -pkeyopt ec_paramgen_curve:P-256 -days 365 -keyout "%KEY%" -out "%CERT%" -subj "/CN=orchestra-control-center" -addext "subjectAltName=IP:127.0.0.1,IP:%DETECTED_IP%,DNS:localhost" >nul 2>&1
        if %errorlevel% neq 0 (
            echo   [quickstart] ERROR: openssl failed. Is OpenSSL installed?
            goto :err
        )
    )
)

:: Certificate fingerprint
for /f "tokens=1" %%f in ('openssl x509 -in "%CERT%" -outform DER ^| openssl dgst -sha256 ^| findstr /r "^[0-9a-f]"') do set "CERT_FP=%%f"
if "%CERT_FP%"=="" (
    for /f "tokens=2" %%f in ('openssl x509 -in "%CERT%" -outform DER ^| openssl dgst -sha256') do set "CERT_FP=%%f"
)

:: ── 6. Agent profile ──────────────────────────────────────────────────

if not exist "%PROFILE_PATH%" (
    echo   [quickstart] Creating default outbound profile: %PROFILE_PATH%
    (
        echo # Auto-generated by scripts/quickstart.bat
        echo target_os               = "%OS%"
        echo target_arch             = "%ARCH%"
        echo c2_address              = "%DETECTED_IP%:%AGENT_PORT%"
        echo encryption_key          = "%AES_KEY%"
        echo c_server_secret         = "%AGENT_SECRET%"
        echo server_cert_fingerprint = "%CERT_FP%"
        echo features                = ["outbound-c"]
        echo package                 = "agent"
        echo bin_name                = "agent-standalone"
    ) > "%PROFILE_PATH%"
    echo   [quickstart] Wrote %PROFILE_PATH%
) else (
    echo   [quickstart] Re-using existing profile %PROFILE_PATH%
)

:: ── 7. Build agent payload ────────────────────────────────────────────

echo   [quickstart] Building agent payload for profile '%PROFILE_NAME%'...
"%BUILDER_BIN%" build "%PROFILE_NAME%"
if %errorlevel% neq 0 goto :err

set "PAYLOAD=dist\%PROFILE_NAME%.enc"
if not exist "%PAYLOAD%" set "PAYLOAD=dist\%PROFILE_NAME%"
if not exist "%PAYLOAD%" (
    echo   [quickstart] ERROR: expected payload in dist\ after build
    goto :err
)

:: ── 8. Server configuration ───────────────────────────────────────────

if not exist "%SERVER_CFG%" (
    echo   [quickstart] Writing %SERVER_CFG%...
    (
        echo # Auto-generated by scripts/quickstart.bat
        echo http_addr           = "0.0.0.0:%HTTP_PORT%"
        echo agent_addr          = "0.0.0.0:%AGENT_PORT%"
        echo agent_shared_secret = "%AGENT_SECRET%"
        echo admin_token         = "%ADMIN_TOKEN%"
        echo audit_log_path      = "secrets/orchestra-audit.jsonl"
        echo static_dir          = "orchestra-server/static"
        echo tls_cert_path       = "%CERT%"
        echo tls_key_path        = "%KEY%"
        echo command_timeout_secs = 30
    ) > "%SERVER_CFG%"
    echo   [quickstart] Wrote %SERVER_CFG%
) else (
    echo   [quickstart] Re-using existing %SERVER_CFG%
)

:: ── 9. Build Control Center ───────────────────────────────────────────

echo   [quickstart] Building Orchestra Control Center...
cargo build --release -p orchestra-server
if %errorlevel% neq 0 goto :err

:: ── 10. Print summary ─────────────────────────────────────────────────

echo.
echo ================================================================================
echo   Orchestra Quickstart complete.
echo.
echo   Dashboard URL     : https://%DETECTED_IP%:%HTTP_PORT%/
echo   Admin bearer token: %ADMIN_TOKEN%
echo   Server config     : %SERVER_CFG%
echo   Agent profile     : %PROFILE_PATH%
echo   Agent payload     : %PAYLOAD%
echo   TLS fingerprint   : %CERT_FP%
echo.
echo   -- Next steps -----------------------------------------------------------------
echo.
echo   1. Start the Control Center:
echo.
echo        target\release\orchestra-server.exe --config %SERVER_CFG%
echo.
echo   2. Open the dashboard ^(accept self-signed cert^):
echo.
echo        https://%DETECTED_IP%:%HTTP_PORT%/
echo.
echo   3. Copy %PAYLOAD% to a target endpoint and run:
echo.
echo        agent-standalone.exe
echo.
echo   4. The agent appears in the dashboard within a few seconds.
echo.
echo   -- Advanced -------------------------------------------------------------------
echo.
echo   Interactive wizard:    scripts\setup.sh
echo   Verify prerequisites:  scripts\verify-setup.sh
echo   Full documentation:    docs\QUICKSTART.md
echo.
echo   Reminder: only deploy to systems you own or are authorised to manage.
echo ================================================================================
echo.

if "%SKIP_SERVER%"=="1" goto :done

set /p "START_NOW=  Start the Orchestra Control Center now? [y/N] "
if /i not "%START_NOW%"=="y" (
    echo   [quickstart] Skipped server start. Run manually with the command above.
    goto :done
)

echo   [quickstart] Starting Control Center...
target\release\orchestra-server.exe --config "%SERVER_CFG%"
set "RC=%errorlevel%"
popd
exit /b %RC%

:done
popd
exit /b 0

:err
echo   [quickstart] Failed. See errors above.
popd
exit /b 1
